CREATE TABLE LOAN_ACCOUNTS 
(
Accno CHAR(4),
Cust_name VARCHAR(15),
Loan_Amount	decimal(10,2),
Installments INT,
int_rate decimal(10,2),
Start_date varchar(30),
Interest decimal(10,2)
);
DESCRIBE LOAN_ACCOUNTS;

ALTER TABLE LOAN_ACCOUNTS
ADD category varchar(21); 
SELECT * FROM LOAN_ACCOUNTS;

INSERT INTO LOAN_ACCOUNTS(Accno,Cust_name,Loan_Amount,Installments,int_rate,Start_date)VALUES(1001,'R.K.GUPTA','300000.00',36,12.00,'19-JULY-2009'),
(1002,'S.P Sharma',500000.00,48,10.00,'22-March-2008'),(1003,'K.P Jain',300000.00,36,NULL,'3-August-2007'),
(1004,'M.P Yadav',800000.00,60,10.00,'12-June-2008'),(1005,'S.P Sinha',200000.00,36,12.50,'1-March-2010'),
(1006,'P. Sharma',700000.00,60,12.50,'6-May-2008'),(1007,'K.S Dhall',500000.00,48,NULL,'3-May-2008');
SELECT * FROM LOAN_ACCOUNTS;

UPDATE LOAN_ACCOUNTS SET  int_rate = 11.50 WHERE Accno = 1003;
UPDATE LOAN_ACCOUNTS SET  int_rate = 11.50 WHERE Accno = 1007;
SELECT * FROM LOAN_ACCOUNTS;

Update Loan_Accounts set int_rate = int_rate + 0.5 where Loan_Amount > 400000;
SELECT * FROM LOAN_ACCOUNTS;

Update Loan_Accounts set Interest = (Loan_amount * Int_rate* installments)/(12*100);
SELECT * FROM LOAN_ACCOUNTS;

DELETE  FROM LOAN_ACCOUNTS WHERE Start_date < '2008';
SELECT * FROM LOAN_ACCOUNTS;

DELETE FROM LOAN_ACCOUNTS WHERE Cust_name like 'k%';
SELECT * FROM LOAN_ACCOUNTS;

SELECT * FROM LOAN_ACCOUNTS WHERE Installments < 40;

SELECT Accno , Loan_amount FROM LOAN_ACCOUNTS WHERE START_DATE > '2009-04-01';

SELECT int_rate FROM LOAN_ACCOUNTS WHERE START_DATE > '2009-04-01';

SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME like '%SHARMA';

SELECT Cust_name, Loan_Amount FROM LOAN_ACCOUNTS WHERE Cust_name like 'a%';

SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%a%';

SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE NOT(CUST_NAME LIKE '%P%');
DESCRIBE LOAN_ACCOUNTS;

SELECT * FROM LOAN_ACCOUNTS ORDER BY  LOAN_AMOUNT ASC;

SELECT * FROM LOAN_ACCOUNTS ORDER BY  START_DATE DESC;

SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT, START_DATE DESC;

SELECT * FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE 'K%';

SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE IS NULL;

SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE is NOT NULL;

SELECT DISTINCT LOAN_AMOUNT FROM LOAN_ACCOUNTS ;

SELECT * FROM LOAN_ACCOUNTS WHERE START_DATE >'2008-12-31' AND  Installments >36;

SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT <500000 OR  INT_RATE >12;

SELECT * FROM LOAN_ACCOUNTS WHERE YEAR(START_DATE)='2009';

SELECT * FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT BETWEEN 400000 AND  500000;

SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE Installments IN(26,36,48);