SELECT CUSTOMER.CID,CUSTOMER_NAME,ACCOUNTS.ACCNO,BRANCH_CITY FROM ACCOUNTS,BRANCH,DEPOSITOR,CUSTOMER WHERE BRANCH.BID=ACCOUNTS.BID AND ACCOUNTS.ACCNO=DEPOSITOR.ACCNO AND DEPOSITOR.CID=CUSTOMER.CID
AND BRANCH.BRANCH_CITY='C3'
GROUP BY DEPOSITOR.CID HAVING COUNT(DISTINCT BRANCH.BID)=(SELECT COUNT(BID) FROM BRANCH WHERE BRANCH_CITY='C3');